baseURL = "http://michaelhealy.space/digital-revolutions-eportfolio/"
languageCode = "en-us"
title = "Digital Revolutions and Convergence Culture"
publishdir = "docs"
theme = "gohugo-theme-ananke"
disqusShortname = "digitalrevolutions"
SectionPagesMenu = "main"
DefaultContentLanguage = "en"
MetaDataFormat = "toml"
paginate = 10
canonifyURLs = true

[params]
  description = "Michael Healy's Fall 2017 ePortfolio"
  dateFormat = "Jan 2, 2006"
  twitter = "mhealy_rhet"
  instagram = "mjhealy"
  github = "mjh16"
  favicon = "/img/share.png"
  background_color_class = "bg-moon-gray"
  featured_image = "/img/station.jpg"

[taxonomies]
  category = "categories"
  tag = "tags"
